version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    hostname: postgres

  redis:
    image: 'redis:4.0.10'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  
  website:
    restart: always
    depends_on:
      - postgres
      - redis
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - 'gems:/gems'

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  postgres:
  redis:
  gems:

